<?php

namespace App\Http\Controllers;

use App\Jobs\SendCertificateJob;
use App\Models\ConstancyGeneralHistory;
use App\Models\DocumentConfiguration;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CertificateSendingController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $history = ConstancyGeneralHistory::with('user')
            ->latest()
            ->paginate(10);

        return view('certificate_sending.index', compact('history'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $configurations = DocumentConfiguration::where('is_active', true)
            ->with('event')
            ->latest()
            ->get();

        return view('certificate_sending.create', compact('configurations'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'document_configuration_id' => 'required|exists:document_configurations,id',
            'csv_file' => 'required|file|mimes:csv,txt|max:2048',
        ]);

        $config = DocumentConfiguration::findOrFail($request->document_configuration_id);

        // Store CSV
        $path = $request->file('csv_file')->store('csv_uploads', 'public');

        // Parse CSV
        $file = fopen(storage_path('app/public/' . $path), 'r');
        $header = fgetcsv($file);

        // Normalize headers: lowercase, trim, remove BOM if present
        $header = array_map(function ($h) {
            return trim(strtolower(preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $h)));
        }, $header);

        $rows = [];
        while (($row = fgetcsv($file)) !== false) {
            if (count($row) === count($header)) {
                $rows[] = array_combine($header, $row);
            }
        }
        fclose($file);

        if (empty($rows)) {
            return back()->withErrors(['csv_file' => 'El archivo CSV está vacío o no tiene el formato correcto.']);
        }

        // Create History Record
        $history = ConstancyGeneralHistory::create([
            'total_registros' => count($rows),
            'procesados_exitosos' => 0,
            'procesados_fallidos' => 0,
            'qrs_generados' => 0, // Not strictly tracking QRs individually here, but could
            'errores' => [],
            'user_id' => Auth::id(),
            'csv_file_path' => $path,
        ]);

        // Dispatch Jobs
        foreach ($rows as $row) {
            // Ensure email exists
            if (empty($row['email'])) {
                $history->increment('procesados_fallidos');
                $errors = $history->errores ?? [];
                $errors[] = ['email' => 'N/A', 'error' => 'Email missing in CSV row', 'time' => now()->toDateTimeString()];
                $history->update(['errores' => $errors]);
                continue;
            }

            SendCertificateJob::dispatch($config, $row, $history->id);
        }

        return redirect()->route('certificate-sending.index')
            ->with('success', 'Proceso de envío iniciado. Se están procesando ' . count($rows) . ' registros.');
    }

    /**
     * Display the specified resource.
     */
    public function show(ConstancyGeneralHistory $history)
    {
        return view('certificate_sending.show', compact('history'));
    }

    public function downloadTemplate(DocumentConfiguration $documentConfiguration)
    {
        $headers = ['email']; // Email is always required

        // Extract placeholders from text elements
        if ($documentConfiguration->text_elements) {
            foreach ($documentConfiguration->text_elements as $element) {
                if (isset($element['text'])) {
                    // Match {variable} pattern
                    if (preg_match_all('/\{(\w+)\}/', $element['text'], $matches)) {
                        foreach ($matches[1] as $match) {
                            if (!in_array($match, $headers)) {
                                $headers[] = $match;
                            }
                        }
                    }
                }
            }
        }

        // Also check for folio if it's not auto-generated (though usually it is)
        // If the user wants to override folio from CSV, they can add 'folio' column.
        // But usually folio is generated by the system or config.
        // Let's add 'folio' as optional if it's in the text elements (already covered above)
        // or if we want to explicitly allow it. For now, regex extraction is sufficient.

        $callback = function () use ($headers) {
            $file = fopen('php://output', 'w');
            fputcsv($file, $headers);
            fclose($file);
        };

        $filename = 'plantilla_' . Str::slug($documentConfiguration->document_name) . '.csv';

        return response()->stream($callback, 200, [
            "Content-type" => "text/csv",
            "Content-Disposition" => "attachment; filename=$filename",
            "Pragma" => "no-cache",
            "Cache-Control" => "must-revalidate, post-check=0, pre-check=0",
            "Expires" => "0"
        ]);
    }
}
